apiVersion: v1
kind: Pod
metadata:
  name: awscli
  namespace: default
spec:
  containers:
  - command:
    - sleep
    - inf
    image: docker.io/amazon/aws-cli
    name: awscli
    envFrom:
      - configMapRef:
          name: test-obc
      - secretRef:
          name: test-obc
    volumeMounts:
      - name: test-pvc
        mountPath: /data
  volumes:
    - name: test-pvc
      persistentVolumeClaim:
        claimName: test-pvc
